import { IWatchlist, IWatchlistData } from './watchlist.types'

// id bigint generated by default as identity primary key,
// user_id uuid references auth.users not null,
// auction_id bigint references public.auctions not null,
// created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL

export class Watchlist implements IWatchlist {
  readonly auctionId: number
  readonly uid: string // uuid

  constructor (data: IWatchlistData) {
    this.auctionId = data.auctionId
    this.uid = data.uid
  }
}
