import { IBid, IBidData } from './bid.types'

// id bigint generated by default as identity primary key,
// amount integer not null,
// auction_id bigint references public.auctions not null,
// user_id uuid references auth.users not null,
// created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL

export class Bid implements IBid {
  readonly id?: number
  readonly amount: number
  readonly auctionId: number
  readonly userId: string
  readonly createdAt?: Date | string

  constructor (data: IBidData) {
    this.amount = data.amount
    this.auctionId = data.auctionId
    this.userId = data.userId
  }
}
