create table public.auctions (
  id int4 generated by default as identity not null primary key,
  name varchar not null,
  description text,
  createdAt timestamptz not null default now(),
  updatedAt timestamptz not null default now(),
  startDate timestampz,
  endDate timestampz,
  startAmount float4,
  featured BOOLEAN,
  enabled BOOLEAN,
  slug VARCHAR NOT NULL,
  ownerId VARCHAR NOT NULL
)

-- 2. Enable RLS
grant select, insert
on auctions
to public;

alter table auctions
enable row level security;

-- 3. Create Policies
create policy "Anon can read auction information."
on auctions for select using (
  auth.role() = 'anon'
);

-- Trigger function every time auctions are updated
create trigger on_auctions_updated
before update on public.auctions
for each row execute procedure public.trigger_set_timestamp();
